### ISSUE TITLE
Character of 줄표(―) is U+2015, not em dash (U+2014)

### ISSUE THREAD

**Issue by yous** [dahlia/seonbi#14]
Referring to [부록 15. 줄표( ― )](https://kornorms.korean.go.kr/regltn/regltnView.do?regltn_code=0001&regltn_no=714#a789) of 한글 맞춤법, the character of 줄표 is [U+2015 HORIZONTAL BAR](https://www.compart.com/en/unicode/U+2015). The em dash is [U+2014 EM DASH](https://www.compart.com/en/unicode/U+2014).

**Comment by dahlia** [comment]
NIKL always has used improper Unicode characters for punctuation marks, which violate Unicode's key concept: <q>Unicode encodes characters, not glyphs.</q> For example, [they use mathematical inequality symbols for citations.][1] Hence, we should not take their literal Unicode uses, but should guess their intention and choose carefully proper Unicode characters instead.

I believe what you addressed is just an instance of their improper Unicode uses… U+2015 HORIZONTAL BAR (`―`) purposes to quote and is followed by a quotation (usually a single sentence and hardly takes multiple paragraphs).  As it's basically alternatives to paired quotations marks, the below two examples are equivalent:

 1.  > ―우리 많이 살았다.
     >
     > ―야.
     >
     > ―니 여한이 없제?
     >
     > ―야, 없십니다.
     >
     > ―그라믄 됐다. 나도 여한이 없다.

 2.  > “우리 많이 살았다.”
     >
     > “야.”
     >
     > “니 여한이 없제?”
     >
     > “야, 없십니다.”
     >
     > “그라믄 됐다. 나도 여한이 없다.”

Basically NIKL's *Hangul Orthography* does not cover such unpaired quotation mark.

On the other hand, according to the explanation of 줄표 from NIKL's *Hangul Orthography*, Appx XV. more corresponds to the use of em dashes IMHO:

> 제목 다음에 표시하는 부제의 앞뒤에 쓴다.
>
> 예: 이번 토론회의 제목은 ‘역사 바로잡기 — 근대의 설정 —’이다.
> 예: ‘환경 보호 — 숲 가꾸기 —’라는 제목으로 글짓기를 했다.
>
> 다만, 뒤에 오는 줄표는 생략할 수 있다.
>
> 예: 이번 토론회의 제목은 ‘역사 바로잡기 — 근대의 설정’이다.
> 예: ‘환경 보호 — 숲 가꾸기’라는 제목으로 글짓기를 했다.

—[〈한글 맞춤법〉 부록 15. 줄표][2]

> A dash may be used in connection with side-heads, whether the following text is run in or paragraphed. Good style calls for a period before the dash when run in (see 80a, 84b, 91):
> 
> > 2\. *The language of the New Testament.*—The lexicons of Grimm-Thayer, Cremer, and others . . . .
> >
> > Nᴏᴛᴇ.—The foregoing has been taken from . . . .
> >
> > Biblical criticism in other denominations—
> > &emsp;A most interesting article appeared in the Expository Times . . . .

—*The Chicago Manual of Style*, “Quotations,” Rule 226.

Note that 줄표 in Korean orthography functionally resembles [wave dashes][3] (波ダッシュ) in Japanese orthography, which is parallel to en/em dashes in English orthography again:

> - To separate a title from a subtitle on the same line; in English a colon is used for this purpose.
> - To mark subtitles: 〜概要〜

[1]: https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=142051&pageIndex=1
[2]: https://kornorms.korean.go.kr/regltn/regltnView.do?regltn_code=0001&regltn_no=789#a789
[3]: https://en.wikipedia.org/wiki/Japanese_punctuation#Wave_dash

**Comment by yous** [comment]
Thank you for the detailed explanation. When I first realized that 한글 맞춤법 uses U+2015 HORIZONTAL BAR, I thought it's because there is no concept of en dash and em dash in Korean, and they used U+2015 as it's somewhat neutral character for the usage. But U+2015 also has its purpose and usage as you mentioned.

I've searched to check whether 한글 맞춤법 uses wrong character for the purpose or they've chosen it intentionally, and found this: [문장 부호의 문자코드 값은?](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=71016) ([archive link](https://web.archive.org/web/20201114105132/https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=71016)). So they are already using the both U+2014 EM DASH and U+2015 HORIZONTAL BAR, and they don't care about the purpose of characters.

Referring to [줄표](https://ko.wikipedia.org/wiki/%EC%A4%84%ED%91%9C) in Wikipedia, it seems that some old JIS encodings used U+2015 HORIZONTAL BAR by mistake. [EUC-KR](https://encoding.spec.whatwg.org/euc-kr.html) also has U+2015 in their table (6185, `\x{A1AA}`). In Windows, you can input U+2015 by pressing ㄱ, 한자 (5th character of 3rd page). I think this also led some mixed usage of U+2014 and U+2015, as it's easier to input U+2015 on Windows (at least, in past).

Put these all together, using U+2014 would be correct. Thanks for the clarification again.
