### ISSUE TITLE
Keep dyno awake with Uptime Robot

### ISSUE THREAD

**Issue by channprj** [dahlia/seonbi#16]
## Summary

- If an app has a free web dyno, and that dyno receives no web traffic in a 30-minute period, it will sleep.
- Sometimes [seonbi API](http://seonbi.herokuapp.com/) hangs or too slow because of **dyno sleeping**.
  - It also affects when you call the seonbi API with iOS Shortcuts.
- Using [Uptime Robot](https://uptimerobot.com/), you can make http requests every five minutes, and also **it is free**!
  - It makes your dyno keep awake.

## Reference

- [Dyno Sleeping - Heroku](https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping)
- [Uptime Robot](https://uptimerobot.com/)

**Comment by dahlia** [comment]
Just configured a monitor to <https://seonbi.herokuapp.com/> on Uptime Robot. It will never sleep from now on.  Thank you for the advice!

**Comment by channprj** [comment]
Thank you so much! 👀✨🎉☺️
