### ISSUE TITLE
Plain text mode besides (X)HTML mode

### ISSUE THREAD

**Issue by dahlia** [dahlia/seonbi#18]
Seonbi currently provides two modes for input/output formatting:

- HTML
- XHTML

However, sometimes we need to apply adjustments on text *before* it's compiled to HTML, or it won't be compiled to HTML at all.  For such demands, it's good to have one more mode: plain text.

Fortunately, it apparently is not that difficult to implement:

1. Escape the whole input to HTML character entities (or simply put it to a CDATA section).
2. Make adjustments on it.
3. Unescape the whole output.

**Comment by dahlia** [comment]
Now the Boolean option `xhtml` is replaced by the new option `contentType`, which should be one of `text/html` and `application/xhtml+xml`.  Two tasks to do remain:

- [ ] Add `text/plain` type.
- [ ] Add [`text/markdown` type][1].
- [ ] Rename `sourceHtml` field to `sourceContent` or `content` in HTTP API.  /cc @channprj @moreal 

[1]: https://datatracker.ietf.org/doc/html/rfc7763

**Comment by dahlia** [comment]
Now we have 4 modes:

<img width="463" alt="HTML, XHTML, Plain text, Markdown" src="https://user-images.githubusercontent.com/12431/142034001-bcaba949-fdd0-4556-8ae8-129fd23a4f39.png">

**Comment by channprj** [comment]
Thank you 👍🏼
