### ISSUE TITLE
Automate Apple silcion build

### ISSUE THREAD

**Issue by dahlia** [dahlia/seonbi#23]
<https://cirrus-ci.org/>

It looks promising.  It supports Linux ARM, Apple silicon Macs, and FreeBSD.

**Comment by dahlia** [comment]
This also looks cool: <https://github.com/actions/runner-images/issues/2187#issuecomment-1293622278>.

**Comment by dahlia** [comment]
[Good news!](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/)

**Comment by moreal** [comment]
Hi @dahlia, is this issue resolved by https://github.com/dahlia/seonbi/commit/93affc13dcdb1b6758253b94f961cdedad211867?

**Comment by dahlia** [comment]
Oh, yes! I'm closing this.
